linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style
      - opinionated

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gomnd
  fast: false

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

run:
  go: '1.19'
